<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_CONTACT US</name>
   <tag></tag>
   <elementGuidId>579702b7-1ebe-43c3-a4bc-78fdba95ef6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2[name=&quot;contactme&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[@name='contactme']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>afa04a89-3af7-4a8d-82f4-3c8dd14544c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>contactme</value>
      <webElementGuid>13e1e8ce-b92f-4cb5-9318-adcc04fecb76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>section_header</value>
      <webElementGuid>d1037238-eb61-4239-8e23-3e727c608914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CONTACT US</value>
      <webElementGuid>b771be1b-25c2-4c19-8407-5f60f9f766e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contact_me&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12 text-center&quot;]/h2[@class=&quot;section_header&quot;]</value>
      <webElementGuid>1eaa8a50-48a9-4da0-9a53-9e246775ef50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@name='contactme']</value>
      <webElementGuid>373e90ea-aaa6-4c4c-a521-f90a9e20831e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='contact_me']/div/div/div/h2</value>
      <webElementGuid>4a274fc3-e9fa-4bc3-874b-d00926e4e81f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WebdriverUniversity.com (New Approach To Learning)'])[1]/following::h2[1]</value>
      <webElementGuid>8adafa14-bf0c-4067-8318-7e652e80ba28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toggle navigation'])[1]/following::h2[1]</value>
      <webElementGuid>5dafc4e6-73bb-4046-8d23-09c9bf6cd460</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::h2[1]</value>
      <webElementGuid>9f3b21c2-746c-4ad8-8543-66dd70e2f32f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::h2[1]</value>
      <webElementGuid>670186e3-50de-4816-b067-a07f31a78804</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CONTACT US']/parent::*</value>
      <webElementGuid>5ec1a400-fab1-4599-a394-01f818caafe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>f3277d0a-36d4-4d18-acfe-925e15b13ab2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@name = 'contactme' and (text() = 'CONTACT US' or . = 'CONTACT US')]</value>
      <webElementGuid>0aeddd27-bc37-4b83-aa08-e7d031bb0504</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
