<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Dropped</name>
   <tag></tag>
   <elementGuidId>0d887054-b9aa-4215-9933-a60549034e8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#droppable > p</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='droppable']/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>5359308a-b42d-4410-88d6-f9ef74d07a19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dropped!</value>
      <webElementGuid>c0133e45-440c-4bfb-8c3f-21a8a4b13418</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;droppable&quot;)/p[1]</value>
      <webElementGuid>7c989275-ab2c-4f53-baa6-ead8680bab63</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='droppable']/p</value>
      <webElementGuid>bedf9b13-526b-45fa-8c2d-3f163c2abbb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DRAG ME TO MY TARGET!'])[1]/following::p[1]</value>
      <webElementGuid>c1a857b5-f54a-41f4-9c90-c0b297e21346</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The Key to Success is to take massive ACTION!'])[1]/following::p[2]</value>
      <webElementGuid>65ca2db8-2147-4f3c-a960-748b16d22b65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Double Click Me!'])[1]/preceding::p[1]</value>
      <webElementGuid>ddf74cf8-e199-47fc-82c9-6b2407d178dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p</value>
      <webElementGuid>40be593a-188b-4ae2-81ce-5614f05cf3c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Dropped!' or . = 'Dropped!')]</value>
      <webElementGuid>f63d8f62-d1a7-4378-a584-b26beba69caf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
